name: penatu
description: "Flutter Laundry Management App"
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## UI
  # Icon
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1

  # Widget
  fl_chart: ^0.68.0
  modal_bottom_sheet: ^3.0.0
  dotted_border: ^2.1.0

  # Helper
  image: ^4.2.0
#  cached_network_image: ^3.3.1
#  animations: ^2.0.11
#  flutter_staggered_animations: ^1.1.1
#  dynamic_color: ^1.7.0

  ##  Network

  # Supabase
  supabase_auth_ui: ^0.4.4
  supabase_flutter: ^2.5.3

  # API Fetch
  http: ^1.2.1

  # Local Storage
  shared_preferences: ^2.2.3

  # env
  flutter_dotenv: ^5.1.0

  # State Management
  flutter_bloc: ^8.1.5

  # Helper
  get_it: ^7.7.0
  intl: ^0.19.0
  logger: ^2.3.0
  equatable: ^2.0.5
  lottie: ^3.1.2

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/ic_launcher.png
  color_dark: "#ffffff"
  #  background_image_dark: "assets/dark-background.png"
  image_dark: assets/icons/ic_launcher.png
  #branding_dark: assets/dart_dark.png

  android_12:
    #    image: assets/icons/ic_launcher_light.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
    #    image_dark: assets/icons/ic_launcher_light.png
    color_dark: "#ffffff"
    icon_background_color_dark: "#ffffff"

flutter_launcher_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  #  flutter_lints: ^3.0.0
  # Change package name
  change_app_package_name: ^1.3.0

  # Generate Asset
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/anims/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env