name: penatu
description: "Flutter Laundry Management App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1

  # Supabase
  supabase_auth_ui: ^0.4.4
  supabase_flutter: ^2.5.3

  flutter_dotenv: ^5.1.0

  intl: ^0.19.0

  image: ^4.2.0
  cached_network_image: ^3.3.1

  http: ^1.2.1
  shared_preferences: ^2.2.3

  logger: ^2.3.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.7.0
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/ic_launcher.png
  color_dark: "#ffffff"
  #  background_image_dark: "assets/dark-background.png"
  image_dark: assets/icons/ic_launcher.png
  #branding_dark: assets/dart_dark.png

  android_12:
    #    image: assets/icons/ic_launcher_light.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
    #    image_dark: assets/icons/ic_launcher_light.png
    color_dark: "#ffffff"
    icon_background_color_dark: "#ffffff"

flutter_launcher_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  #  flutter_lints: ^3.0.0

  # Generate Asset
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/anims/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env